import React, { useState } from 'react';
import { View, Text, TextInput, ScrollView, TouchableOpacity, StyleSheet, Alert } from 'react-native';
import { colors, fonts, radius } from '../theme/theme';
import { useTheme } from '../context/ParishContext';
import ScreenHeader from '../components/ScreenHeader';
import BccPicker from '../components/BccPicker';
import PhoneField from '../components/PhoneField';
import EmailField from '../components/EmailField';
import api from '../services/api';

function Field({ label, value, onChangeText, placeholder, keyboardType, required }) {
  return (
    <View style={{ marginBottom: 14 }}>
      <Text style={styles.label}>{label}{required ? ' *' : ''}</Text>
      <TextInput
        style={styles.input}
        value={value}
        onChangeText={onChangeText}
        placeholder={placeholder}
        placeholderTextColor={colors.inkSoft}
        keyboardType={keyboardType}
      />
    </View>
  );
}

// Step 1 of the family-creation flow. This screen only creates the family
// row — family_code is generated by the database, and head_member_id starts
// null. On success we hand straight off to AddMemberScreen (isHeadMember:
// true) to collect the head of family. See AddMemberScreen and
// api.setFamilyHead for the rest of the flow, and FamilyListScreen for how
// a family that never gets a head (flow abandoned partway through) stays
// visible and resumable rather than becoming orphaned data.
export default function AddFamilyScreen({ navigation }) {
  const t = useTheme();
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({
    house_name: '',
    address_line1: '',
    address_line2: '',
    place: '',
    district: '',
    state: '',
    pincode: '',
    phone: '',
    email: '',
    ward: '',
    basic_christian_community: '',
  });

  const set = (key) => (val) => setForm((f) => ({ ...f, [key]: val }));

  const canSave = form.house_name.trim().length > 0;

  const save = async () => {
    if (!canSave) {
      Alert.alert('Missing details', 'House name is required.');
      return;
    }
    setSaving(true);
    try {
      const family = await api.createFamily(form);
      // Straight into "add head of family" — no dead-end screen in between.
      navigation.replace('AddMember', {
        familyId: family.id,
        familyName: family.house_name,
        isHeadMember: true,
      });
    } catch (e) {
      Alert.alert('Could not create family', e.message || 'Something went wrong.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <View style={styles.flex}>
      <ScreenHeader title="Add Family" navigation={navigation} />
      <ScrollView contentContainerStyle={{ padding: 16 }}>
        <Text style={styles.hint}>
          Family code is generated automatically. Next you'll add the head of family.
        </Text>
        <Field label="House name" value={form.house_name} onChangeText={set('house_name')} placeholder="e.g. Parish House" required />
        <Field label="Address line 1" value={form.address_line1} onChangeText={set('address_line1')} placeholder="Address line 1" />
        <Field label="Address line 2" value={form.address_line2} onChangeText={set('address_line2')} placeholder="Address line 2" />
        <Field label="Place" value={form.place} onChangeText={set('place')} placeholder="Place" />
        <Field label="Ward" value={form.ward} onChangeText={set('ward')} placeholder="e.g. Ward 1" />
        <BccPicker value={form.basic_christian_community} onChange={set('basic_christian_community')} />
        <Field label="District" value={form.district} onChangeText={set('district')} placeholder="District" />
        <Field label="State" value={form.state} onChangeText={set('state')} placeholder="State" />
        <Field label="Pincode" value={form.pincode} onChangeText={set('pincode')} placeholder="Pincode" keyboardType="number-pad" />
        <PhoneField label="Phone" value={form.phone} onChange={set('phone')} dialable={false} />
        <EmailField label="Email" value={form.email} onChange={set('email')} mailable={false} />

        <TouchableOpacity style={[styles.saveBtn, { backgroundColor: t.primary }, !canSave && { opacity: 0.5 }]} onPress={save} disabled={saving || !canSave}>
          <Text style={styles.saveBtnText}>{saving ? 'Creating…' : 'Create family & continue'}</Text>
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.stone },
  hint: { fontFamily: fonts.body, fontSize: 12.5, color: colors.inkSoft, marginBottom: 16 },
  label: { fontFamily: fonts.bodyMedium, fontSize: 12, color: colors.inkSoft, marginBottom: 6 },
  input: { backgroundColor: colors.white, borderRadius: radius.sm, paddingHorizontal: 14, paddingVertical: 12, fontFamily: fonts.body, fontSize: 14, color: colors.ink, borderWidth: 1, borderColor: colors.divider },
  saveBtn: { borderRadius: radius.sm, paddingVertical: 15, alignItems: 'center', marginTop: 10, marginBottom: 30 },
  saveBtnText: { color: colors.white, fontFamily: fonts.bodySemi, fontSize: 15 },
});
